version: '3'

services:
  development:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PSSWD}
      POSTGRES_DB: lucas_db
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'